name: Docker Build

on:
  push:
    paths:
      - "Dockerfile"
  pull_request:
    paths:
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t speed-test .
